import itertools
from typing import List, Dict
EXP_GROUPS = dict()
model_list = [
    {'name': 'semseg', 'loss': 'cons_point_loss',
     'base': 'fcn8_vgg16',
     'n_channels': 3, 'n_classes': 1},
    {'name': 'semseg', 'loss': 'cons_point_loss_multi',
        'base': 'fcn8_vgg16', 'n_channels': 3, 'n_classes': 5}

]


def template_exp_spine(n_classes: int = 6, base: str = 'fcn8_vgg16', debug: bool = False, sources: List[str] = ['xVertSeg', 'USiegen', 'MyoSegmenTUM'], blob_points: int = 1, bg_points: int = -1, batch_size=6, loss: List[str] = ['unsupervised_rotation_loss', 'rot_point_loss_multi', 'prior_extend', 'separation_loss']) -> Dict:
    dataset = {
        'n_classes': n_classes,
        'name': 'spine_dataset',
        'sources' : sources,
        'blob_points': blob_points,
        'bg_points': bg_points}
    dataset_size = {
            split: 10 if debug else 'all' for split in [
                'test',
                'train',
                'val']}
    model = {
        'base': base,
        'loss': loss,
        'n_channels': 3,
        'n_classes' : n_classes,
        'name': 'semseg' if n_classes == 1 else 'inst_seg',
    }
    return {
        'batch_size': 6,
        'dataset': dataset,
        'dataset_size' : dataset_size,
        'lr': 10**(-4),
        'max_epoch': 10 if debug else 55,
        'model': model,
        'num_channels': 1,
        'optimizer': 'adam'
    }




EXP_GROUPS['debug_weakly_spine_dataset_c6'] = [
    template_exp_spine(
        debug=True,
        sources=[s]) for s in [
            'xVertSeg',
            'USiegen',
        'MyoSegmenTUM']] + [template_exp_spine(debug=True, base=b) for b in ['fcn8_vgg16', 'fcn8_resnet']]

EXP_GROUPS['weakly_spine_dataset_c6'] = [template_exp_spine(debug=False, blob_points=2, bg_points=5, base=b) for b in ['fcn8_vgg16', 'fcn8_resnet']]

# EXP_GROUPS = {'debug_weakly_spine_dataset_c1': [{'batch_size': 1,
#  'dataset': {'n_classes': 1,
#  'name': 'spine_dataset',
#  'blob_points': 2,
#  'bg_points': 5},
#  'dataset_size': {'test': 2,
#   'train': 3,
#   'val': 2},
#  'lr': 0.0001,
#  'max_epoch': 10,
#  'model': {'base': 'fcn8_vgg16',
#    'loss': ['unsupervised_flip_loss', 'cons_point_loss'],
#    'n_channels': 3,
#    'n_classes': 1,
#    'name': 'semseg'},
#  'num_channels': 1,
#  'optimizer': 'adam'}],
#   'debug_weakly_spine_dataset_c6': [{'batch_size': 6,
#  'dataset': {'n_classes': 6,
#  'name': 'spine_dataset',
#  'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#  'blob_points': 2,
#  'bg_points': 5},
#  'dataset_size': {'test': 10,
#   'train': 10,
#   'val': 10},
#  'lr': 0.0001,
#  'max_epoch': 5,
#  'model': {'base': 'fcn8_vgg16',
#    'loss': [ 'unsupervised_rotation_loss', 'rot_point_loss_multi', 'prior_extend', 'separation_loss' ],
#    'n_channels': 3,
#    'n_classes': 6,
#    'name': 'inst_seg'},
#  'num_channels': 1,
#  'optimizer': 'adam'},
#
# {'batch_size': 6,
#  'dataset': {'n_classes': 6,
#  'name': 'spine_dataset',
#  'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#  'blob_points': 2,
#  'bg_points': 5},
#  'dataset_size': {'test': 10,
#   'train': 10,
#   'val': 10},
#  'lr': 0.0001,
#  'max_epoch': 5,
#  'model': {'base': 'fcn8_vgg16',
#    'loss': ['unsupervised_flip_loss', 'cons_point_loss_multi'],
#    'n_channels': 3,
#    'n_classes': 6,
#    'name': 'inst_seg'},
#  'num_channels': 1,
#  'optimizer': 'adam'},
#
# {'batch_size': 6,
#  'dataset': {'n_classes': 6,
#  'name': 'spine_dataset',
#  'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#  'blob_points': 2,
#  'bg_points': 5},
#  'dataset_size': {'test': 10,
#   'train': 10,
#   'val': 10},
#  'lr': 0.0001,
#  'max_epoch': 5,
#  'model': {'base': 'fcn8_resnet',
#    'loss': [ 'unsupervised_rotation_loss', 'rot_point_loss_multi' ],
#    'n_channels': 3,
#    'n_classes': 6,
#    'name': 'inst_seg'},
#  'num_channels': 1,
#  'optimizer': 'adam'},
#
#  {'batch_size': 6,
#  'dataset': {'n_classes': 6,
#  'name': 'spine_dataset',
#  'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#  'blob_points': 2,
#  'bg_points': 5},
#  'dataset_size': {'test': 10,
#   'train': 10,
#   'val': 10},
#  'lr': 0.0001,
#  'max_epoch': 5,
#  'model': {'base': 'fcn8_vgg16',
#    'loss': [ 'unsupervised_rotation_loss', 'rot_point_loss_multi' ],
#    'n_channels': 3,
#    'n_classes': 6,
#    'name': 'inst_seg'},
#  'num_channels': 1,
#  'optimizer': 'adam'}
#
#  ],
#   'weakly_spine_dataset_c1': [{'batch_size': 6,
#    'dataset': {'n_classes': 1,
#    'name': 'spine_dataset',
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 55,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': ['unsupervised_flip_loss', 'cons_point_loss'],
#  'n_channels': 3,
#  'n_classes': 1,
#  'name': 'semseg'},
#    'num_channels': 1,
#    'optimizer': 'adam'}],
#   'weakly_spine_dataset_c6': [
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 55,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'cross_entropy' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 55,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'weighted_cross_entropy' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 21,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'cross_entropy' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 21,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'unsupervised_rotation_loss', 'rot_point_loss_multi', 'prior_extend', 'separation_loss' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 55,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'unsupervised_rotation_loss', 'prior_extend', 'separation_loss' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 55,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'unsupervised_rotation_loss', 'prior_extend' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 55,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'unsupervised_rotation_loss', 'rot_point_loss_multi', 'separation_loss' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#    {'batch_size': 6,
#    'dataset': {'n_classes': 6,
#    'name': 'spine_dataset',
#    'sources' : ['xVertSeg', 'USiegen', 'MyoSegmenTUM'],
#    'blob_points': 2,
#    'bg_points': 5},
#    'dataset_size': {'train': 'all', 'val': 'all'},
#    'lr': 0.0001,
#    'max_epoch': 55,
#    'model': {'base': 'fcn8_vgg16',
#  'loss': [ 'unsupervised_rotation_loss', 'rot_point_loss_multi' ],
#  'n_channels': 3,
#  'n_classes': 6,
#  'name': 'inst_seg'},
#    'num_channels': 1,
#    'optimizer': 'adam'},
#   ]}
#
