FROM jupyter/datascience-notebook

ENV JUPYTER_ENABLE_LAB true
ENV PIP_TARGET /home/jovyan/work/python_packages
ENV PYTHONPATH /home/jovyan/work/python_packages
ENV TORCH_HUB /home/jovyan/work
ENV TORCH_HOME /home/jovyan/work

WORKDIR /home/jovyan/

COPY requirements_wisenet.txt /opt/app/requirements.txt
WORKDIR /opt/app/
USER root
RUN apt update -y && \
    apt install python3-dev python3-pip python3-venv -y && \
    apt-get install tree && \
    pip3 install --upgrade pip && \
    pip3 install Cython

RUN pip3 install -r requirements.txt && \
    mkdir /root/space && \
    mkdir /root/space/temp/
WORKDIR /root/space/

RUN mkdir -p /home/jovyan/work/python_packages

EXPOSE 8080

COPY --chown=jovyan:users . /home/jovyan/covid

CMD ["/bin/sh", "-c", "start-notebook.sh --ip=0.0.0.0 --port=8080 --no-browser --LabApp.token='' --LabApp.allow_remote_access=True --LabApp.allow_origin='*' --LabApp.disable_check_xsrf=True"]

